---
- name: Create virtual network interface card
  azure_rm_networkinterface:
    resource_group: "{{azure_resourcegroup_name}}"
    name: "{{vm_name}}-nic"
    virtual_network: "{{azure_vnet_name}}"
    subnet: "{{subnet_name}}"
    security_group: "{{azure_security_group_name}}"
    ip_configurations:
      - name: main-network
        private_ip_address: "{{vm_private_ip}}"
        private_ip_allocation_method : "Static"

- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{azure_resourcegroup_name}}"
    name: "{{vm_name}}"
    vm_size: "{{azure_vm_size}}"
    admin_username: "{{vm_username}}"
    admin_password: "{{vm_password}}"
    ssh_password_enabled: true
    network_interfaces: "{{vm_name}}-nic"
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: "18.04-LTS"
      version: latest
