cloud:
  provider: azure
  options:
    AZURE_CLIENT_ID: ***REMOVED***
    AZURE_TENANT: ***REMOVED***
    AZURE_SECRET: ***REMOVED***
    AZURE_SUBSCRIPTION_ID: ***REMOVED***

networks: # TODO: only single network
  - name: main
    cidr: 10.0.1.0/24

vpn:
  network: 10.0.2.0/24
  port: 4300

hosts:
  manager:
    hostname: main
    username: azureuser
    password: testPw4321
    network: main # TODO: now it is useless
    ip: 10.0.1.20
    image: ubuntu # TODO: now it is useless
    attacks:
      - type: sqlmap
        options:
          sqlmap_url: http://10.0.1.6/?country=test
  vulnboxes:
    - hostname: test1
      username: azureuser
      password: testPw4321
      network: main # TODO: now it is useless
      ip: 10.0.1.6
      image: ubuntu # TODO: now it is useless
      services:
        - type: apache_php_mysql
          options:
            schema_directory: static/sqli/db/schema.sql
            web_source_directory: static/sqli/web
