project:
  name: cyberrange
  location: "West Europe"

network:
  cidr: 10.0.0.0/16
  subnets:
    - name: main
      cidr: 10.0.1.0/24
    - name: secondary
      cidr: 10.0.2.0/24

vpn:
  subnet: main
  lan_ip: 10.0.1.200
  vpn_subnet: 10.0.100.0/24

hosts:
  - name: host1
    username: testuser1
    password: "1bH.NP53B&IP"
    ip: 10.0.1.5
    subnet: main
    services:
      - name: apache_php_mysql
  - name: host2
    username: testuser2
    password: "1bH.NP53B&IP"
    ip: 10.0.1.6
    subnet: main
    services:
      - name: sqlmap
        vars:
          sqlmap_url: "http://10.0.1.5"
      - name: apache_php_mysql
  - name: host3
    username: testuser3
    password: "1bH.NP53B&IP"
    ip: 10.0.2.5
    subnet: secondary
