---
- name: Install apache, php and mysql
  ansible.builtin.package:
    name:
      - mysql-server
      - apache2
      - php
      - php-bcmath
      - php-bz2
      - php-intl
      - php-gd
      - php-mbstring
      - php-mysql
      - php-zip
      - python3-pymysql
    state: present

- name: Copy mysql schema
  ansible.builtin.copy:
    src: assets/db/schema.sql
    dest: /tmp/schema.sql

- name: Import database schema
  community.mysql.mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: all
    state: import
    target: /tmp/schema.sql

- name: Remove apache default site
  ansible.builtin.command: rm -r /var/www/html

- name: Copy web files
  ansible.builtin.copy:
    src: assets/web/
    dest: /var/www/html
