---
- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: "{{azure_resourcegroup_name}}"
    allocation_method: Static
    name: "{{azure_publicip_name}}"
  register: output_ip_address
- name: Dump public IP for VM which will be created
  local_action: copy content={{ output_ip_address.state.ip_address }} dest=../../.public_ip

- name: Create virtual network interface card for external network
  azure_rm_networkinterface:
    resource_group: "{{azure_resourcegroup_name}}"
    name: "{{vm_name}}-nic"
    virtual_network: "{{azure_vnet_name}}"
    subnet: "{{subnet_name}}"
    security_group: "{{azure_security_group_name}}"
    ip_configurations:
      - name: main-network
        private_ip_address: "{{vm_private_ip}}"
        private_ip_allocation_method : "Static"
        public_ip_address_name: "{{azure_publicip_name}}"

- name: Create main VM
  azure_rm_virtualmachine:
    resource_group: "{{azure_resourcegroup_name}}"
    name: "{{vm_name}}"
    vm_size: "{{azure_vm_size}}"
    admin_username: "{{vm_username}}"
    admin_password: "{{vm_password}}"
    ssh_password_enabled: true
    network_interfaces: "{{vm_name}}-nic"
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: "18.04-LTS"
      version: latest
